event_inherited()
movement_cost = 3 * room_speed
attack_cost = 1.5 * room_speed
max_action_bar = 3 * room_speed
action_bar = 0
range = 2
HP = 70
max_HP = 70
HP_regeneration_rate = 0.1
damage = 3
damage_reduction = 0
accuracy = 1
base_accuracy = accuracy
evasiveness = 0.5
altitude = "ground"
mana = 50
max_mana = 100
mana_regen_rate_per_sec = 0.6
experience_to_give = 100
slow = createSpell(SPELLS.slow, "q")
invisibility = createSpell(SPELLS.invisibility, "w")
slow.lvl = 1
slow.autocast = 1
buttons = ["q", "w"]
skills = [slow, invisibility]
slow_icon_animation_index = 0
slow_icon_animation_speed = 8 //frames per sec

attack_target = function() {attack_target_magic_projectile()}
